const action_types = {
    CHANGE_SHOW_WAIT:'CHANGE_SHOW_WAIT',
    TOGGLE_ALL: 'TOGGLE_ALL',
    TOGGLE_ENABLE_UNTIL: 'TOGGLE_ENABLE_UNTIL',
    TOGGLE_FILTER: 'TOGGLE_FILTER',
    TOGGLE_IS_PRIVATE: 'TOGGLE_IS_PRIVATE',
    TOGGLE_SELECTED: 'TOGGLE_SELECTED',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    UPDATE_DAYS: 'UPDATE_DAYS',
    UPDATE_SP_USER: 'UPDATE_SP_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_CHART: 'UPDATE_CHART',
    UPDATE_LIST_SORT: 'UPDATE_LIST_SORT',
    UPDATE_SINGLE_SEARCH: 'UPDATE_SINGLE_SEARCH',
    UPDATE_PLAYLIST_NAME: 'UPDATE_PLAYLIST_NAME',
    UPDATE_PLAYLIST_INFO: 'UPDATE_PLAYLIST_INFO',
    UPDATE_LAST_UPDATE: 'UPDATE_LAST_UPDATE',
    UPDATE_START_TIME: 'UPDATE_START_TIME',
    UPDATE_SINCE: 'UPDATE_SINCE',
    UPDATE_UNTIL: 'UPDATE_UNTIL',
    UPDATE_SONGS_PER_DAY: 'UPDATE_SONGS_PER_DAY',
    UPDATE_SHOW_LAST: 'UPDATE_SHOW_LAST',

};

module.exports = action_types;